force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotizacion</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mecanismo__c/Mecanismo__c.object-meta.xml
<CustomObject>
    <label>Mecanismo</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mecanismos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mecanismo__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mecanismo__c/fields/PrecioSinFactura__c.field-meta.xml
<CustomField>
    <fullName>PrecioSinFactura__c</fullName>
    <label>Precio Sin Factura</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mecanismo__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Roller</fullName>
            </value>
            <value>
                <fullName>Panel Oriental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tela__c/Tela__c.object-meta.xml
<CustomObject>
    <label>Tela</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Telas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tela__c/fields/PrecioIVA__c.field-meta.xml
<CustomField>
    <fullName>PrecioIVA__c</fullName>
    <label>Precio con IVA</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tela__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cristal</fullName>
            </value>
            <value>
                <fullName>Blackout</fullName>
            </value>
            <value>
                <fullName>Sunscreen</fullName>
            </value>
            <value>
                <fullName>Traslucidas</fullName>
            </value>
            <value>
                <fullName>Transparente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ventana__c/Ventana__c.object-meta.xml
<CustomObject>
    <label>Ventana</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ventanas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ventana__c/fields/Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion__c</fullName>
    <label>Cotizacion</label>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Ventanas</relationshipLabel>
    <relationshipName>Ventanas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ventana__c/fields/Mecanismo__c.field-meta.xml
<CustomField>
    <fullName>Mecanismo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mecanismo</label>
    <referenceTo>Mecanismo__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ventana__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ventana__c/fields/Tela__c.field-meta.xml
<CustomField>
    <fullName>Tela__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tela</label>
    <referenceTo>Tela__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CotizadorController.cls
public class CotizadorController {
  @AuraEnabled(cacheable=true)
  public static List<Tela__c> getTelas(String tipoTela) {
    if (!String.isEmpty(tipoTela)) {
      return [
        SELECT Id, Name, Tipo__c, Precio__c, PrecioIVA__c, PrecioSinFactura__c
        FROM Tela__c
        WHERE Tipo__c = :tipoTela
      ];
    }
    return new List<Tela__c>();
  }

  @AuraEnabled(cacheable=true)
  public static List<Mecanismo__c> getMecanismos() {
    return [
      SELECT Id, Name, Tipo__c, Precio__c, PrecioIVA__c, PrecioSinFactura__c
      FROM Mecanismo__c
    ];
  }

  @AuraEnabled
  public static Cotizacion__c saveCotization(List<Ventana__c> ventanas) {
    Cotizacion__c cotizacion = new Cotizacion__c(Name = 'Referencia');
    insert cotizacion;
    for (Ventana__c v : ventanas) {
      v.Cotizacion__c = cotizacion.Id;
    }
    insert ventanas;
    return cotizacion;
  }
}